version: 0.0
Resources:
  - LambdaFunction:
      Type: AWS::Lambda::Function
      Properties:
        Name: add-product
        Alias: Production
        CurrentVersion: 1
        TargetVersion: 2
        DeploymentHooks:
          BeforeAllowTraffic: "lambda_function_before_allow_traffic"
          AfterAllowTraffic: "lambda_function_after_allow_traffic"
  - LambdaFunction:
      Type: AWS::Lambda::Function
      Properties:
        Name: update-product
        Alias: Production
        CurrentVersion: 1
        TargetVersion: 2
        DeploymentHooks:
          BeforeAllowTraffic: "lambda_function_before_allow_traffic"
          AfterAllowTraffic: "lambda_function_after_allow_traffic"
