version: 0.0
Resources:
  - LambdaFunction:
      Type: AWS::Lambda::Function
      Properties:
        Name: update-product
        Alias: Production
        CurrentVersion: 1
        TargetVersion: 2
