name: Deploy Lambda Functions

on:
  push:
    branches:
      - main # Change this to match your branch name

jobs:
  deploy_add_product:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Set AWS Credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region us-east-1

      - name: Upload Add Product Deployment Artifact to S3
        run: |
          cd add-products
          zip -r add-products.zip .
          mv add-products.zip ../
          cd ..          
          aws s3 cp add-products.zip s3://deployment-ecom/add-products.zip --region us-east-1

      - name: Create CodeDeploy Deployment for Add Product Lambda
        run: |
          aws deploy create-deployment \
              --application-name ecom \
              --deployment-group-name ecom-deploy-add \
              --s3-location bucket=deployment-ecom,key=add-products.zip,bundleType=zip \
              --region us-east-1

  deploy_update_product:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Set AWS Credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region us-east-1

      - name: Upload Update Product Deployment Artifact to S3
        run: |
          cd update-products
          zip -r update-products.zip .
          mv update-products.zip ../
          cd .. 
          aws s3 cp update-products.zip s3://deployment-ecom/update-products.zip --region us-east-1

      - name: Create CodeDeploy Deployment for Update Product Lambda
        run: |
          aws deploy create-deployment \
              --application-name ecom \
              --deployment-group-name ecom-deploy-update \
              --s3-location bucket=deployment-ecom,key=update-products.zip,bundleType=zip \
              --region us-east-1
